<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyTitle></AssemblyTitle>
    <ApplicationIcon>KpzRepository_lib_icon.ico</ApplicationIcon>
    <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
    <Title>KpzRepository.SqlServer</Title>
    <Authors>Maxim Mihaluk</Authors>
    <Description>A lightweight and flexible repository pattern implementation for .NET 8, providing a unified interface for database operations across SQL Server.</Description>
    <Copyright>Maxim Mihaluk</Copyright>
    <PackageIcon>KpzRepository_lib_icon.png</PackageIcon>
    <PackageProjectUrl>https://kpzrepository.com</PackageProjectUrl>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <RepositoryUrl>https://github.com/malicone/KpzRepository</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <PackageTags>repository-pattern;database;sqlserver</PackageTags>
    <PackageReleaseNotes>Initial build</PackageReleaseNotes>
    <PackageLicenseFile>LICENSE.txt</PackageLicenseFile>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="KpzRepository_lib_icon.ico" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\LICENSE.txt">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Data.SqlClient" Version="7.0.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\KpzRepository\KpzRepository.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Update="README.md">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>

</Project>
