<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <ApplicationIcon>KpzRepository_lib_icon.ico</ApplicationIcon>
    <PackageIcon>KpzRepository_lib_icon.png</PackageIcon>
    <Title>KpzRepository</Title>
    <Authors>Maxim Mihaluk</Authors>
    <Description>A lightweight and flexible repository pattern implementation for .NET 8, providing a unified interface for database operations across SQL Server, PostgreSQL, and SQLite. Install specific database provider you need - KpzRepository.SqlServer, KpzRepository.Sqlite and so on. The core package KpzRepository is included automatically.</Description>
    <Copyright>Maxim Mihaluk</Copyright>
    <PackageProjectUrl>https://kpzrepository.com</PackageProjectUrl>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <RepositoryUrl>https://github.com/malicone/KpzRepository</RepositoryUrl>
    <PackageTags>repository-pattern;database;sqlserver;postgresql;sqlite</PackageTags>
    <PackageReleaseNotes>Initial build</PackageReleaseNotes>
    <PackageLicenseFile>LICENSE.txt</PackageLicenseFile>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="KpzRepository_lib_icon.ico">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </EmbeddedResource>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="..\LICENSE.txt">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </EmbeddedResource>
    <EmbeddedResource Include="KpzRepository_lib_icon.png">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </EmbeddedResource>
    <None Include="..\README.md">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Dapper" Version="2.1.72" />
    <PackageReference Include="Dapper.Contrib" Version="2.0.78" />
    <PackageReference Include="System.Reflection" Version="4.3.0" />
  </ItemGroup>

  <ItemGroup>
    <None Update="KpzRepository_lib_icon.png">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
    <None Update="LICENSE.txt">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>

</Project>
