<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <ApplicationIcon>KpzRepository_lib_icon.ico</ApplicationIcon>
    <Title>KpzRepository.PostgreSql</Title>
    <Description>A lightweight and flexible repository pattern implementation for .NET 8, providing a unified interface for database operations across PostgreSQL.</Description>
    <Copyright>Maxim Mihaluk</Copyright>
    <PackageProjectUrl>https://kpzrepository.com</PackageProjectUrl>
    <PackageIcon>KpzRepository_lib_icon.png</PackageIcon>
    <RepositoryUrl>https://github.com/malicone/KpzRepository</RepositoryUrl>
    <PackageTags>repository-pattern;database;postgresql</PackageTags>
    <PackageReleaseNotes>Initial build</PackageReleaseNotes>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PackageLicenseFile>LICENSE.txt</PackageLicenseFile>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="KpzRepository_lib_icon.png" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="KpzRepository_lib_icon.ico">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="KpzRepository_lib_icon.png">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </EmbeddedResource>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Npgsql" Version="10.0.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\KpzRepository\KpzRepository.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Update="LICENSE.txt">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
    <None Update="README.md">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>

</Project>
